export const LIMITS = {
  FREE_MAX_PHOTOS_PER_TRIP: 10,
  PRO_MAX_PHOTOS_PER_TRIP: 100,
  FREE_MAX_DOCUMENTS_PER_TRIP: 3,
  PRO_MAX_DOCUMENTS_PER_TRIP: 30,
  FREE_MAX_ACTIVE_TRIPS: 3,
  MAX_IMAGE_WIDTH_PX: 1000,
  IMAGE_COMPRESS_QUALITY: 0.6,
} as const
